import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/page";
import Footer from "@/components/footer/page";
import { Toaster } from "react-hot-toast";
import Cart from "./(pages)/cart/page";
import CartContextProvider from "@/context/CartContext";
import WishlistContextProvider from "@/context/wishlistContext";
import MySessionProvider from "@/components/MySessionProvider/MySessionProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Market Corner App",
  description: "Generated by Hadeer Farag",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
       <MySessionProvider>
         <CartContextProvider>
          <WishlistContextProvider>
            <Navbar />
            <main className="flex-1 container mx-auto px-24 py-8">
              {children}
              <Toaster />
            </main>
            <Footer />
          </WishlistContextProvider>
        </CartContextProvider>
       </MySessionProvider>
      </body>
    </html>
  );
}
